### ISSUE TITLE
Runtime error on newer devices

### ISSUE THREAD

**Issue by charliefoxtwo** [n6xej/RRStructureScannerSwift4#3]
The error is the same as the one detailed [here](https://forums.structure.io/t/announcing-structure-sdk-0-8-1-improved-trackers-and-turntable-support/8281).

`*** Terminating app due to uncaught exception AVCameraCalibration, reason: We want to use AV Intrinsics, but we're not getting them! Make sure that you have set conn.cameraIntrinsicsMatrixDeliveryEnabled = YES on the AVCaptureConnection object (before you commit the AVCaptureSession configuration). ***`

**Comment by n6xej** [comment]
Thanks, I had already had a different implementation ready to check in that check if the enables image stabilization if supported by the device.
