### ISSUE TITLE
Crash when connecting camera

### ISSUE THREAD

**Issue by Nastaszja** [n6xej/RRStructureScannerSwift4#4]
Hi! We wanted to test your application on my Ipad Air.
For testing it, we just load your code on Xcode and built/run it without any modification.
When we run the application, the app crashes when we connect our camera.

our iOS version : 11.4
our XCode version : 9.3

**Comment by n6xej** [comment]
There are other things that can cause it to crash, but I suspect it is the version of the SDK you are using. Version 0.81 version of the structure SDK does not work with the A7GPU which is what is in the iPad Air. Version 0.7x will work or try an older version of xCode that does not support iOS11

If "conn.isCameraIntrinsicMatrixDeliverySupported" does not return true when setting up the camera it will crash.
